### ISSUE TITLE
Need Windows Compile Instructions

### ISSUE THREAD

**Issue by ghost-ng** [audibleblink/HoleySocks#3]
Can you provides instructions for compiling a standalone binary on Windows?

**Comment by audibleblink** [comment]
Hey there. Provided you have a working go1.16+ development environment and Make is installed, it should be as easy as running `make windows`. If you don't want to/can't use `make`, just be sure the `configs/ssh.json` file exists, and from the project root run

```bash
go build
```

**Comment by ghost-ng** [comment]
thanks!  I wasnt familiar with any "make" commands for windows, thanks for the tip
